# Generated by Django 5.2.12 on 2026-03-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_document_invite_token_documentmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="instruction",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="suggestion_type",
            field=models.CharField(
                choices=[
                    ("rewrite", "Rewrite"),
                    ("improve", "Improve clarity"),
                    ("shorten", "Shorten"),
                    ("expand", "Expand"),
                    ("custom", "Custom instruction"),
                ],
                max_length=20,
            ),
        ),
    ]
