# Generated by Codex on 2026-03-18

from django.db import migrations, models
from django.db.models import Q


def ensure_onboarding_column(apps, schema_editor):
    table = "core_document"
    connection = schema_editor.connection
    columns = {
        column.name
        for column in connection.introspection.get_table_description(
            connection.cursor(), table
        )
    }

    if "is_onboarding" in columns:
        return

    if "is_showcase" in columns:
        schema_editor.execute(
            f"ALTER TABLE {table} RENAME COLUMN is_showcase TO is_onboarding"
        )
        return

    schema_editor.execute(
        f"ALTER TABLE {table} "
        "ADD COLUMN is_onboarding boolean NOT NULL DEFAULT FALSE"
    )


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_suggestion_custom_instruction"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    ensure_onboarding_column,
                    reverse_code=noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="document",
                    name="is_onboarding",
                    field=models.BooleanField(
                        default=False,
                        help_text=(
                            "Superuser-only. Pins this document as the public onboarding "
                            "entry point and allows anonymous suggestion requests."
                        ),
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=Q(is_onboarding=True),
                fields=("is_onboarding",),
                name="unique_onboarding_document",
            ),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="origin",
            field=models.CharField(
                choices=[("member", "Member"), ("public", "Public")],
                default="member",
                max_length=20,
            ),
        ),
    ]
